twitch:
    channel: TwitchUserName
    token: oauth:XXXXXXXXXXX
http:
    port: 8090
    url:
aggreg:
    stacksize: 60
    channels:
        - megadamage
smtp:
    server: localhost
    port: 25
    username:
    password:
